name: "Deployment"
concurrency:
  group: deploy
  cancel-in-progress: true

on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: PSKZ_IP
    steps:
      - uses: actions/checkout@v5
      - name: Deploy to PS.KZ
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.PSKZ_IP }}
          username: ${{ secrets.PSKZ_USER }}
          password: ${{ secrets.PSKZ_PASSWORD }}
          key: ${{secrets.PSKZ_SSH_KEY }}
          script: |
            cd /root/ai-qoima-tools
            git pull origin main
            docker compose down
            docker compose up -d --build
